version: '3.8'

services:
  web:
    container_name: sql_web
    env_file: .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: sql_redis
    image: "redis:alpine3.19"
    ports:
      - "6379:6379"